# Generated by Django 4.1.7 on 2023-03-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='category',
        ),
        migrations.AddField(
            model_name='nutrient',
            name='_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrients.nutrientcategory'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='rda',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=15),
        ),
    ]
