# Generated by Django 4.1.7 on 2023-03-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0002_remove_nutrient_category_nutrient__category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=15),
        ),
    ]
