# Generated by Django 4.1.7 on 2023-03-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0003_nutrient_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nutrient',
        ),
        migrations.DeleteModel(
            name='NutrientCategory',
        ),
    ]
