# Generated by Django 4.1.7 on 2023-03-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('fat', models.DecimalField(decimal_places=2, default=100, max_digits=15)),
                ('calories', models.DecimalField(decimal_places=2, default=100, max_digits=15)),
                ('proteins', models.DecimalField(decimal_places=2, default=100, max_digits=15)),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=100, max_digits=15)),
                ('serving', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rda', models.DecimalField(decimal_places=2, default=100, max_digits=15)),
                ('wiki', models.TextField()),
                ('required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Nutrient Category',
                'verbose_name_plural': 'Nutrient Categories',
            },
        ),
        migrations.CreateModel(
            name='NutrientInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=100, max_digits=15)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.nutrient')),
            ],
        ),
        migrations.AddField(
            model_name='nutrient',
            name='_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.nutrientcategory'),
        ),
        migrations.CreateModel(
            name='FoodInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=100)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.meal')),
            ],
        ),
    ]
