# Generated by Django 4.1.7 on 2023-05-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='caption',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
