# Generated by Django 4.1.7 on 2023-04-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='_category',
        ),
        migrations.AddField(
            model_name='nutrient',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='NutrientCategory',
        ),
    ]
