# Generated by Django 4.1.7 on 2023-03-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinstance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=15),
        ),
    ]
