# Generated by Django 4.1.7 on 2023-05-03 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_description',
            field=models.CharField(default='haha', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='user',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
