# Generated by Django 4.1.7 on 2023-04-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Specialist', 'Specialist')], max_length=50),
        ),
    ]
