# Generated by Django 4.1.7 on 2023-05-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_user_customer_id_user_specialist_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Breakfast', max_length=50),
        ),
    ]
