# Generated by Django 4.1.7 on 2023-05-06 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_meal_options_alter_meal_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
